# Generated by Django 5.1.1 on 2024-12-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindt',
            name='admin_id',
            field=models.CharField(blank=True, default='565b7a7e', max_length=8, unique=True),
        ),
    ]
