# Generated by Django 5.1.1 on 2024-12-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SuperAdmin', '0002_alter_admindt_admin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindt',
            name='admin_id',
            field=models.CharField(blank=True, default='0e368631', max_length=8, unique=True),
        ),
    ]
