# Generated by Django 5.1.1 on 2024-12-14 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subadmindt',
            name='subadmin_id',
            field=models.CharField(blank=True, default='14685142', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='subadmindt',
            name='subadmin_last_login',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 15, 5, 25, 34, 344525, tzinfo=datetime.timezone.utc), verbose_name='last login'),
        ),
    ]
