# Generated by Django 5.1.1 on 2024-12-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetail',
            name='last_login',
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='Expire_date',
            field=models.DateTimeField(default=None, verbose_name='Expire login'),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='api_key',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='f70830cd', max_length=8, unique=True),
        ),
    ]
