# Generated by Django 5.1.1 on 2024-12-17 08:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_remove_clientdetail_last_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_SYMBOL_QTY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=50, null=True)),
                ('SYMBOL', models.CharField(blank=True, max_length=50, null=True)),
                ('QUANTITY', models.FloatField(blank=True, null=True)),
                ('trade', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SYMBOL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SYMBOL', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='af2c1c87', max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='GROUP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GROUP', models.CharField(max_length=10)),
                ('min_quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('max_quantity', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.clientdetail')),
                ('symbols', models.ManyToManyField(related_name='groups', to='client.symbol')),
            ],
        ),
    ]
