# Generated by Django 5.1.1 on 2024-12-17 08:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_client_symbol_qty_symbol_alter_clientdetail_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user',
        ),
        migrations.AddField(
            model_name='clientdetail',
            name='client_Group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.group'),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='c6984ccf', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='GROUP',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='group',
            name='max_quantity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='group',
            name='min_quantity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
