# Generated by Django 5.1.1 on 2024-12-17 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_group_user_clientdetail_client_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='user_id',
            field=models.CharField(default='9ecc79d0', max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='ClientSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.CharField(blank=True, max_length=50, null=True)),
                ('client_id', models.CharField(blank=True, max_length=50, null=True)),
                ('message_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ids', models.CharField(blank=True, max_length=50, null=True)),
                ('TYPE', models.CharField(choices=[('BUY_ENTRY', 'BUY_ENTRY'), ('BUY_EXIT', 'BUY_EXIT'), ('SELL_ENTRY', 'SELL_ENTRY'), ('SELL_EXIT', 'SELL_EXIT')], max_length=10)),
                ('QUANTITY', models.FloatField(blank=True, null=True)),
                ('ENTRY_PRICE', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('EXIT_PRICE', models.DecimalField(blank=True, decimal_places=5, max_digits=12, null=True)),
                ('profit_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cumulative_pl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('SYMBOL', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_signals', to='client.symbol')),
            ],
        ),
    ]
